-- Create table for sales events (Venda-lista de eventos)
create table if not exists venda_eventos (
  id bigint generated by default as identity primary key,
  nome text not null,
  data date not null,
  quem_pagou_freelancers text check (quem_pagou_freelancers in ('Diogo', 'Aziel')),
  criado_por uuid references auth.users(id),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Enable Row Level Security
alter table venda_eventos enable row level security;

-- Create policies
create policy "Usuários autenticados podem ver venda_eventos"
  on venda_eventos for select
  to authenticated
  using (true);

create policy "Usuários autenticados podem criar venda_eventos"
  on venda_eventos for insert
  to authenticated
  with check (auth.uid() = criado_por);

create policy "Usuários autenticados podem atualizar venda_eventos"
  on venda_eventos for update
  to authenticated
  using (true);

create policy "Usuários autenticados podem deletar venda_eventos"
  on venda_eventos for delete
  to authenticated
  using (true);

-- Create trigger for updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_venda_eventos_updated_at
    before update on venda_eventos
    for each row
    execute function update_updated_at_column();
