-- Create table for sales items (Venda-novo evento / itens de venda)
create table if not exists venda_itens (
  id bigint generated by default as identity primary key,
  evento_id bigint references venda_eventos(id) on delete cascade not null,
  nome text not null,
  tipo text check (tipo in ('socio', 'freelancer')) not null,
  valor_vendido decimal(10,2) default 0,
  conta_bancaria decimal(10,2) default 0,
  valor_pago decimal(10,2) default 0,
  valor_liquido decimal(10,2) default 0,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Enable Row Level Security
alter table venda_itens enable row level security;

-- Create policies
create policy "Usuários autenticados podem ver venda_itens"
  on venda_itens for select
  to authenticated
  using (true);

create policy "Usuários autenticados podem criar venda_itens"
  on venda_itens for insert
  to authenticated
  with check (true);

create policy "Usuários autenticados podem atualizar venda_itens"
  on venda_itens for update
  to authenticated
  using (true);

create policy "Usuários autenticados podem deletar venda_itens"
  on venda_itens for delete
  to authenticated
  using (true);

-- Create trigger for updated_at
create trigger update_venda_itens_updated_at
    before update on venda_itens
    for each row
    execute function update_updated_at_column();
