-- Create table for sales expenses (Venda - Despesas do evento)
create table if not exists venda_despesas (
  id bigint generated by default as identity primary key,
  evento_id bigint references venda_eventos(id) on delete cascade not null,
  descricao text not null,
  valor decimal(10,2) not null,
  quem_pagou text check (quem_pagou in ('Diogo', 'Aziel', 'Caixa')) not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Enable Row Level Security
alter table venda_despesas enable row level security;

-- Create policies
create policy "Usuários autenticados podem ver venda_despesas"
  on venda_despesas for select
  to authenticated
  using (true);

create policy "Usuários autenticados podem criar venda_despesas"
  on venda_despesas for insert
  to authenticated
  with check (true);

create policy "Usuários autenticados podem atualizar venda_despesas"
  on venda_despesas for update
  to authenticated
  using (true);

create policy "Usuários autenticados podem deletar venda_despesas"
  on venda_despesas for delete
  to authenticated
  using (true);

-- Create trigger for updated_at
create trigger update_venda_despesas_updated_at
    before update on venda_despesas
    for each row
    execute function update_updated_at_column();
