-- Adicionar colunas financeiras na tabela venda_eventos
ALTER TABLE venda_eventos
ADD COLUMN IF NOT EXISTS total_vendido_site DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS comissao_percentual DECIMAL(5,2) DEFAULT 10.00,
ADD COLUMN IF NOT EXISTS valor_liquido DECIMAL(10,2) GENERATED ALWAYS AS (total_vendido_site - (total_vendido_site * comissao_percentual / 100)) STORED,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;

-- Criar tabela de logs de auditoria
CREATE TABLE IF NOT EXISTS venda_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela TEXT NOT NULL,
    registro_id BIGINT NOT NULL,
    acao TEXT NOT NULL,
    dados_antigos JSONB,
    dados_novos JSONB,
    usuario_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Função para auditoria
CREATE OR REPLACE FUNCTION log_venda_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO venda_audit_logs (tabela, registro_id, acao, dados_antigos, usuario_id)
        VALUES (TG_TABLE_NAME, OLD.id, 'DELETE', row_to_json(OLD), auth.uid());
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO venda_audit_logs (tabela, registro_id, acao, dados_antigos, dados_novos, usuario_id)
        VALUES (TG_TABLE_NAME, NEW.id, 'UPDATE', row_to_json(OLD), row_to_json(NEW), auth.uid());
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO venda_audit_logs (tabela, registro_id, acao, dados_novos, usuario_id)
        VALUES (TG_TABLE_NAME, NEW.id, 'INSERT', row_to_json(NEW), auth.uid());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para venda_eventos
DROP TRIGGER IF EXISTS audit_venda_eventos ON venda_eventos;
CREATE TRIGGER audit_venda_eventos
AFTER INSERT OR UPDATE OR DELETE ON venda_eventos
FOR EACH ROW EXECUTE FUNCTION log_venda_changes();

-- Trigger para venda_itens (opcional, mas bom ter)
DROP TRIGGER IF EXISTS audit_venda_itens ON venda_itens;
CREATE TRIGGER audit_venda_itens
AFTER INSERT OR UPDATE OR DELETE ON venda_itens
FOR EACH ROW EXECUTE FUNCTION log_venda_changes();

-- Trigger para venda_despesas
DROP TRIGGER IF EXISTS audit_venda_despesas ON venda_despesas;
CREATE TRIGGER audit_venda_despesas
AFTER INSERT OR UPDATE OR DELETE ON venda_despesas
FOR EACH ROW EXECUTE FUNCTION log_venda_changes();
